[build]
  publish = "."

[[redirects]]
  from = "/s3-proxy/*"
  to = "https://s3.buckets.ru/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/s3-upload"
  to = "https://s3.buckets.ru/tab-manager/tab-manager-data.xml"
  status = 200
  force = true

[[redirects]]
  from = "/s3-download"
  to = "https://s3.buckets.ru/tab-manager/tab-manager-data.xml"
  status = 200
  force = true

# CORS headers for S3 proxy routes
[[headers]]
  for = "/s3-proxy/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, PUT, POST, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"

[[headers]]
  for = "/s3-upload"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, PUT, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, x-amz-acl, Authorization"

[[headers]]
  for = "/s3-download"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"